### ISSUE TITLE
timex compile error

### ISSUE THREAD

**Issue by beno** [parroty/oauth2ex#14]
Not sure what is going on, but when I include oauth2ex in a project, compilation fails with a DateTime related error in a module called Timex. Looking at deps it seems we are including version 0.19 of this, but the actual [timex module](https://github.com/bitwalker/timex) appears to be around version 3.0.

So I am guessing there are 2 timexes? What am I missing here? Meanwhile I am cloning this library to see if I can get rid of the dependency altogether.

**Comment by parroty** [comment]
Thanks for the comment. I've updated the dependent libraries. https://github.com/parroty/oauth2ex/pull/15
