### ISSUE TITLE
HTTPoison errors

### ISSUE THREAD

**Issue by zweizeichen** [parroty/oauth2ex#8]
Hi,
thank you for creating this package! I have created a fresh project with mix and followed the instructions detailed in the readme. Inside the project directory I created a file named `test.exs` which looks like this:

```elixir
# Setup config parameters (retrive required parameters from OAuth 2.0 providers).
config = OAuth2Ex.config(
  id:            "XXXXX",
  secret:        "XXXXX",
  authorize_url: "XXXXX",
  token_url:     "XXXXX",
  scope:         "XXXXX",
  callback_url:  "http://localhost:4000",
  token_store:   %OAuth2Ex.FileStorage{
                   file_path: System.user_home <> "/test.token"}
)
# -> %OAuth2Ex.Config{authorize_url: "https://accounts.google.com/o/oauth2/auth"...

# Retrieve token from server. It opens authorize_url using browser,
# and then waits for the callback on the local server on port 4000.
token = OAuth2Ex.Token.browse_and_retrieve!(config, receiver_port: 4000)
# -> %OAuth2Ex.Token{access_token: "..."

# Access API server using token.
response = OAuth2Ex.HTTP.get(token, "XXXXX")
# -> %HTTPoison.Response{body: "{\n \"kind\": \"bigquery#projectList...
```

I ran `mix deps.get` to install the packages and then ran `mix run test.exs`to execute my script. I am presented with the correct login page, can authenticate and am then redirected to my local server which claims: `Authorization process completed. Return back to the application to proceed.`. Then, the console program crashes showing the following output:

```
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:hackney_pool, :default)
    src/hackney_connect/hackney_pool.erl:169: :hackney_pool.find_pool/2
    src/hackney_connect/hackney_pool.erl:57: :hackney_pool.checkout/4
    src/hackney_connect/hackney_connect.erl:169: :hackney_connect.socket_from_pool/4
    src/hackney_connect/hackney_connect.erl:30: :hackney_connect.connect/5
    src/hackney_client/hackney.erl:301: :hackney.request/5
    lib/httpoison.ex:44: HTTPoison.request/5
    lib/httpoison.ex:44: HTTPoison.request!/5
```

I do not know what exactly went wrong, maybe it's the wrapper around the HTTPoison requests in `OAuth2Ex.HTTP`or Hackney might not have been initialized correctly.

2 links I stumbled upon while debugging which might be of interest:
https://gist.github.com/asconix/d47d895596353c8eb6b0
https://github.com/benoitc/hackney/issues/63

I really don't know where to go from here and would appreciate any help!

`mix deps` output:
```
* idna 1.0.1 (Hex package)
  locked at 1.0.1 (idna)
  ok
* timex 0.13.3 (Hex package)
  locked at 0.13.3 (timex)
  ok
* ranch 1.0.0 (Hex package)
  locked at 1.0.0 (ranch)
  ok
* jsx 2.4.0 (Hex package)
  locked at 2.4.0 (jsx)
  ok
* exjsx 3.1.0 (Hex package)
  locked at 3.1.0 (exjsx)
  ok
* hackney 0.14.3 (Hex package)
  locked at 0.14.3 (hackney)
  ok
* httpoison 0.5.0 (Hex package)
  locked at 0.5.0 (httpoison)
  ok
* cowlib 1.0.1 (Hex package)
  locked at 1.0.1 (cowlib)
  ok
* cowboy 1.0.0 (Hex package)
  locked at 1.0.0 (cowboy)
  ok
* plug 0.9.0 (Hex package)
  locked at 0.9.0 (plug)
  ok
* oauth2ex 0.0.6 (git://github.com/parroty/oauth2ex.git)
  locked at 1d2f0b0
  ok
```

**Comment by parroty** [comment]
Thank you for the report. As in your comment, it may be caused by hackney is started.
Could you retry by adding `:oauth2ex` the application section of `mix.exs` file? 

```elixir
  def application do
    [ applications: [:logger, :oauth2ex] ]
  end
```

**Comment by zweizeichen** [comment]
Haha - what a stupid mistake. I'm still new to Elixir. :smiley: Now everything is working as intended. Thank you for your help!

**Comment by parroty** [comment]
Please feel free to open an issue. I'm learning elixir and these comments helps understanding!
